yolo_model:

  config_file:
    name: tiny_416.cfg
  weight_file:
    name: yolov3-tiny_277000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - robot
      - football
      - goal
      - center
      - dontcare
