yolo_model:

  config_file:
    name: robocup2020/0827/yolov3-tiny_4.cfg
  weight_file:
    name: robocup2020/0827/yolov3-tiny_4_21000.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - cpoint
      - tpoint
      - lpoint
      - goalpost
      - goal
      - ball
